[package]
name = "number-general"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
description = "A generic number type for Rust which supports basic math and (de)serialization."
license-file = "LICENSE"
readme = "README.md"
repository = "http://github.com/haydnv/number-general.git"

categories = [""]
keywords = ["number", "generic-number", "math", "mathematics"]

[dependencies]
num = "0.3"
safecast = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
