[package]
name = "number-general"
version = "0.3.0"
authors = ["haydnv"]
edition = "2018"
description = "A generic number type for Rust which supports basic math and (de)serialization."
license = "Apache-2.0"
readme = "README.md"
repository = "http://github.com/haydnv/number-general.git"

categories = ["data-structures", "mathematics"]
keywords = ["number", "complex", "float", "integer", "unsigned"]

[dependencies]
async-trait = "0.1"
collate = "0.1"
destream = "0.2"
num = "0.2"
safecast = "0.1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
destream_json = "0.3"
futures = "0.3"
serde_json = "1.0"
